{% set version = "1.7.0" %}

package:
  name: pep8
  version: {{ version }}

source:
  fn: pep8-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pep8/pep8-{{ version }}.tar.gz
  sha256: a113d5f5ad7a7abacef9df5ec3f2af23a20a28005921577b15dd584d099d5900

build:
  entry_points:
    - pep8 = pep8:_main

  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  commands:
    - pep8 --help
    - pep8 --version

about:
  home: http://pep8.readthedocs.org/
  license: MIT License
  summary: 'Python style guide checker'

extra:
  recipe-maintainers:
    - jakirkham
    - pmlandwehr
    - jjhelmus
