{% set name = "pep8" %}
{% set version = "1.7.1" %}
{% set bundle = "tar.gz" %}
{% set hash = "fe249b52e20498e59e0b5c5256aa52ee99fc295b26ec9eaa85776ffdb9fe6374" %}
{% set build = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  entry_points:
    - pep8 = pep8:_main

  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - pep8 --help
    - pep8 --version

about:
  home: https://pep8.readthedocs.org/
  license: MIT
  license_family: MIT
  summary: 'Python style guide checker'
  dev_url: https://github.com/treyhunner/pep8
  doc_url: https://pep8.readthedocs.org/

extra:
  recipe-maintainers:
    - jakirkham
    - pmlandwehr
